
All: CtoF FtoC negate FeetToInches InchesToFeet 10x swapEOR

CtoF: CtoF.s
	gcc CtoF.s -g -o CtoF

FtoC: FtoC.s
	gcc FtoC.s -g -o FtoC

negate: negate.s
	gcc negate.s -g -o negate

FeetToInches: FeetToInches.s
	gcc FeetToInches.s -g -o FeetToInches

InchesToFeet: InchesToFeet.s
	gcc InchesToFeet.s -g -o InchesToFeet

10x: 10x.s
	gcc 10x.s -g -o 10x

swapEOR: swapEOR.s
	gcc swapEOR.s -g -o swapEOR

clean:
	rm -f CtoF FtoC negate FeetToInches InchesToFeet 10x swapEOR





